export interface CompanyMeta {
  name: string;
  slug: string;
  domain: string;
  description: string;
  size: string;
  tags: string[];
  logoPath: string | null;
  website: string;
  vacancyUrl: string;
}

export const COMPANIES_META: CompanyMeta[] = [
  // ─── IT & Tech ────────────────────────────────────────────────────────────────
  {
    name: "Яндекс",
    slug: "yandex",
    domain: "yandex.ru",
    description: "Крупнейшая российская IT-компания: поиск, рекомендательные сервисы, такси, маркетплейс, облако и многое другое.",
    size: "20 000+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/yandex.svg",
    website: "https://yandex.ru",
    vacancyUrl: "https://yandex.ru/jobs",
  },
  {
    name: "ВКонтакте",
    slug: "vk",
    domain: "vk.com",
    description: "Крупнейшая социальная сеть России. Развивают экосистему из мессенджеров, игр, музыки и видео.",
    size: "10 000+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/vk.svg",
    website: "https://vk.com",
    vacancyUrl: "https://jobs.vk.company",
  },
  {
    name: "2GIS",
    slug: "2gis",
    domain: "2gis.ru",
    description: "Картографический сервис и городской справочник. Используется в 500+ городах мира.",
    size: "3 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/2gis.svg",
    website: "https://2gis.ru",
    vacancyUrl: "https://career.2gis.ru",
  },
  {
    name: "Kaspersky",
    slug: "kaspersky",
    domain: "kaspersky.ru",
    description: "Мировой лидер в сфере кибербезопасности. Разрабатывают антивирусные и корпоративные решения.",
    size: "5 000+ сотрудников",
    tags: ["IT", "Безопасность"],
    logoPath: "/logos/kaspersky.svg",
    website: "https://kaspersky.ru",
    vacancyUrl: "https://kaspersky.ru/careers",
  },
  {
    name: "Positive Technologies",
    slug: "positive",
    domain: "ptsecurity.com",
    description: "Российский лидер в сфере информационной безопасности и защиты от киберугроз.",
    size: "2 000+ сотрудников",
    tags: ["IT", "Безопасность"],
    logoPath: "/logos/positive.png",
    website: "https://ptsecurity.com",
    vacancyUrl: "https://www.ptsecurity.com/ru-ru/about/jobs",
  },
  {
    name: "YADRO",
    slug: "yadro",
    domain: "yadro.com",
    description: "Российский производитель IT-оборудования, серверов и систем хранения данных.",
    size: "5 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/yadro.png",
    website: "https://yadro.com",
    vacancyUrl: "https://yadro.com/ru/career",
  },
  {
    name: "SKB Kontur",
    slug: "kontur",
    domain: "kontur.ru",
    description: "Разрабатывают облачные сервисы для бизнеса. Одна из лучших IT-культур в России.",
    size: "8 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/kontur.png",
    website: "https://kontur.ru",
    vacancyUrl: "https://kontur.ru/career",
  },
  {
    name: "Selectel",
    slug: "selectel",
    domain: "selectel.ru",
    description: "Российский облачный провайдер с высокими стандартами инженерной культуры.",
    size: "1 500+ сотрудников",
    tags: ["IT", "Облако"],
    logoPath: "/logos/selectel.svg",
    website: "https://selectel.ru",
    vacancyUrl: "https://selectel.ru/about/jobs",
  },
  {
    name: "LANIT",
    slug: "lanit",
    domain: "lanit.ru",
    description: "Крупнейший российский IT-холдинг. Системная интеграция, разработка ПО, аутсорсинг.",
    size: "15 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/lanit.png",
    website: "https://lanit.ru",
    vacancyUrl: "https://lanit.ru/career",
  },
  {
    name: "КРОК",
    slug: "croc",
    domain: "croc.ru",
    description: "Ведущий системный интегратор России. Облачные сервисы, ИИ, кибербезопасность.",
    size: "3 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/croc.png",
    website: "https://croc.ru",
    vacancyUrl: "https://croc.ru/career",
  },
  {
    name: "1С",
    slug: "1c",
    domain: "1c.ru",
    description: "Ведущий разработчик делового ПО в России. Системы автоматизации учёта и управления.",
    size: "10 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/1c.png",
    website: "https://1c.ru",
    vacancyUrl: "https://1c.ru/about/vacancy.htm",
  },
  {
    name: "Group-IB",
    slug: "groupib",
    domain: "group-ib.ru",
    description: "Мировой лидер в расследовании киберпреступлений и защите от киберугроз.",
    size: "1 000+ сотрудников",
    tags: ["IT", "Безопасность"],
    logoPath: "/logos/groupib.png",
    website: "https://group-ib.ru",
    vacancyUrl: "https://group-ib.ru/career",
  },
  {
    name: "BI.ZONE",
    slug: "bizone",
    domain: "bi.zone",
    description: "Кибербезопасность. Дочерняя компания Сбера, специализирующаяся на защите данных.",
    size: "500+ сотрудников",
    tags: ["IT", "Безопасность"],
    logoPath: "/logos/bizone.png",
    website: "https://bi.zone",
    vacancyUrl: "https://bi.zone/career",
  },
  {
    name: "Cloud.ru",
    slug: "cloudru",
    domain: "cloud.ru",
    description: "Российская облачная платформа. Предоставляют инфраструктурные сервисы бизнесу.",
    size: "2 000+ сотрудников",
    tags: ["IT", "Облако"],
    logoPath: "/logos/cloudru.png",
    website: "https://cloud.ru",
    vacancyUrl: "https://cloud.ru/career",
  },
  {
    name: "Acronis",
    slug: "acronis",
    domain: "acronis.com",
    description: "Глобальная компания в области защиты данных и кибербезопасности. Российские корни.",
    size: "1 500+ сотрудников",
    tags: ["IT", "Безопасность"],
    logoPath: "/logos/acronis.png",
    website: "https://acronis.com",
    vacancyUrl: "https://www.acronis.com/ru-ru/careers",
  },
  {
    name: "JetBrains",
    slug: "jetbrains",
    domain: "jetbrains.com",
    description: "Разрабатывают инструменты для разработчиков: IntelliJ IDEA, Kotlin, PyCharm.",
    size: "2 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/jetbrains.png",
    website: "https://jetbrains.com",
    vacancyUrl: "https://www.jetbrains.com/ru-ru/careers",
  },
  {
    name: "Miro",
    slug: "miro",
    domain: "miro.com",
    description: "Платформа для визуальной совместной работы. Используется командами по всему миру.",
    size: "2 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/miro.png",
    website: "https://miro.com",
    vacancyUrl: "https://miro.com/careers",
  },
  {
    name: "Wrike",
    slug: "wrike",
    domain: "wrike.com",
    description: "Платформа для управления проектами и работой команд. Используется глобально.",
    size: "1 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/wrike.png",
    website: "https://wrike.com",
    vacancyUrl: "https://www.wrike.com/ru/jobs",
  },
  {
    name: "InfoWatch",
    slug: "infowatch",
    domain: "infowatch.ru",
    description: "Разработчик решений для защиты от утечек данных и корпоративной кибербезопасности.",
    size: "500+ сотрудников",
    tags: ["IT", "Безопасность"],
    logoPath: "/logos/infowatch.png",
    website: "https://infowatch.ru",
    vacancyUrl: "https://infowatch.ru/career",
  },
  {
    name: "Авиасейлс",
    slug: "aviasales",
    domain: "aviasales.ru",
    description: "Ведущий сервис поиска авиабилетов с передовой IT-культурой и сильной командой.",
    size: "1 200+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/aviasales.png",
    website: "https://aviasales.ru",
    vacancyUrl: "https://aviasales.ru/about/jobs",
  },
  {
    name: "Додо Инжиниринг",
    slug: "dodo",
    domain: "dodo.pizza",
    description: "IT-подразделение Додо Пицца. Разрабатывают цифровую платформу для сети пиццерий.",
    size: "500+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/dodo.png",
    website: "https://dodo.pizza",
    vacancyUrl: "https://dodo.pizza/ru-ru/jobs",
  },

  // ─── Финтех & Банки ───────────────────────────────────────────────────────────
  {
    name: "Сбер",
    slug: "sber",
    domain: "sber.ru",
    description: "Крупнейший банк и технологическая экосистема России. Инвестируют в AI, ML и цифровые сервисы.",
    size: "300 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/sber.svg",
    website: "https://sber.ru",
    vacancyUrl: "https://rabota.sber.ru",
  },
  {
    name: "Т-Банк",
    slug: "tinkoff",
    domain: "tbank.ru",
    description: "Технологический банк и финансовая экосистема. Один из крупнейших работодателей в финтехе.",
    size: "30 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/tinkoff.svg",
    website: "https://tbank.ru",
    vacancyUrl: "https://careers.tbank.ru",
  },
  {
    name: "Альфа-Банк",
    slug: "alfabank",
    domain: "alfabank.ru",
    description: "Один из крупнейших частных банков с развитым IT-подразделением Alfa Digital.",
    size: "25 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/alfabank.png",
    website: "https://alfabank.ru",
    vacancyUrl: "https://career.alfabank.ru",
  },
  {
    name: "ВТБ",
    slug: "vtb",
    domain: "vtb.ru",
    description: "Государственный банк с масштабным IT-направлением и активной цифровой трансформацией.",
    size: "80 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/vtb.png",
    website: "https://vtb.ru",
    vacancyUrl: "https://hr.vtb.ru/vacancy",
  },
  {
    name: "Точка Банк",
    slug: "tochka",
    domain: "tochka.com",
    description: "Технологичный банк для предпринимателей. Строят финансовые инструменты нового поколения.",
    size: "2 500+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/tochka.png",
    website: "https://tochka.com",
    vacancyUrl: "https://tochka.com/career",
  },
  {
    name: "Совкомбанк",
    slug: "sovcombank",
    domain: "sovcombank.ru",
    description: "Быстрорастущий банк с сильной IT-командой. Активно нанимают разработчиков.",
    size: "15 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/sovcombank.png",
    website: "https://sovcombank.ru",
    vacancyUrl: "https://sovcombank.ru/about/career",
  },
  {
    name: "Райффайзен Банк",
    slug: "raiffeisen",
    domain: "raiffeisen.ru",
    description: "Международный банк с высокими стандартами разработки и сильной IT-культурой.",
    size: "8 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/raiffeisen.png",
    website: "https://raiffeisen.ru",
    vacancyUrl: "https://www.raiffeisen.ru/about/career",
  },
  {
    name: "Газпромбанк",
    slug: "gazprombank",
    domain: "gazprombank.ru",
    description: "Один из системообразующих банков России, активно развивающий digital-направление.",
    size: "20 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/gazprombank.png",
    website: "https://gazprombank.ru",
    vacancyUrl: "https://www.gazprombank.ru/career",
  },
  {
    name: "QIWI",
    slug: "qiwi",
    domain: "qiwi.com",
    description: "Российская платёжная экосистема. Разрабатывают технологии для финансовых сервисов.",
    size: "2 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/qiwi.png",
    website: "https://qiwi.com",
    vacancyUrl: "https://careers.qiwi.ru",
  },
  {
    name: "ДОМ.РФ",
    slug: "domrf",
    domain: "dom.rf",
    description: "Государственный институт развития жилищной сферы с крупным IT-направлением.",
    size: "5 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/domrf.png",
    website: "https://dom.rf",
    vacancyUrl: "https://domrf.ru/about/career",
  },
  {
    name: "Домклик",
    slug: "domclick",
    domain: "domclick.ru",
    description: "Цифровая платформа для покупки и продажи недвижимости от Сбера.",
    size: "3 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/domclick.png",
    website: "https://domclick.ru",
    vacancyUrl: "https://domclick.ru/career",
  },
  {
    name: "АльфаСтрахование",
    slug: "alfastrah",
    domain: "alfastrah.ru",
    description: "Крупнейшая страховая компания России. Активно развивают InsurTech.",
    size: "10 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/alfastrah.png",
    website: "https://alfastrah.ru",
    vacancyUrl: "https://alfastrah.ru/career",
  },
  {
    name: "СберТех",
    slug: "sbertech",
    domain: "sbertech.ru",
    description: "IT-дочерняя компания Сбера. Разрабатывают технологии для всей экосистемы Сбер.",
    size: "10 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/sbertech.png",
    website: "https://sbertech.ru",
    vacancyUrl: "https://sbertech.ru/career",
  },
  {
    name: "Диасофт",
    slug: "diasoft",
    domain: "diasoft.ru",
    description: "Разрабатывают программные продукты для банков и финансовых организаций.",
    size: "3 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/diasoft.png",
    website: "https://diasoft.ru",
    vacancyUrl: "https://diasoft.ru/job",
  },

  // ─── E-commerce & Маркетплейсы ────────────────────────────────────────────────
  {
    name: "Озон",
    slug: "ozon",
    domain: "ozon.ru",
    description: "Один из крупнейших маркетплейсов России. Активно развивают логистику, финтех и облачные сервисы.",
    size: "50 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/ozon.svg",
    website: "https://ozon.ru",
    vacancyUrl: "https://job.ozon.ru",
  },
  {
    name: "Авито",
    slug: "avito",
    domain: "avito.ru",
    description: "Крупнейшая платформа объявлений в России. Развивают маркетплейс, финансовые продукты и технологии.",
    size: "5 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/avito.svg",
    website: "https://avito.ru",
    vacancyUrl: "https://avito.ru/company/jobs",
  },
  {
    name: "Wildberries",
    slug: "wildberries",
    domain: "wildberries.ru",
    description: "Крупнейший маркетплейс России по обороту. Активно развивают технологическую платформу и логистику.",
    size: "100 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/wildberries.svg",
    website: "https://wildberries.ru",
    vacancyUrl: "https://career.wildberries.ru",
  },
  {
    name: "Lamoda",
    slug: "lamoda",
    domain: "lamoda.ru",
    description: "Крупнейший fashion-маркетплейс России. Продают одежду, обувь и аксессуары с быстрой доставкой.",
    size: "10 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/lamoda.svg",
    website: "https://lamoda.ru",
    vacancyUrl: "https://lamoda.ru/about/careers",
  },
  {
    name: "Самокат",
    slug: "samokat",
    domain: "samokat.ru",
    description: "Сервис быстрой доставки продуктов за 15 минут. Активно развивают технологическую платформу.",
    size: "20 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/samokat.svg",
    website: "https://samokat.ru",
    vacancyUrl: "https://samokat.ru/career",
  },
  {
    name: "Мегамаркет",
    slug: "megamarket",
    domain: "megamarket.ru",
    description: "Маркетплейс Сбера. Развивают конкурентоспособную технологическую платформу.",
    size: "5 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/megamarket.png",
    website: "https://megamarket.ru",
    vacancyUrl: "https://megamarket.ru/career",
  },
  {
    name: "DNS",
    slug: "dns",
    domain: "dns-shop.ru",
    description: "Крупнейший ритейлер электроники. Строят собственную масштабную IT-инфраструктуру.",
    size: "20 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/dns.png",
    website: "https://dns-shop.ru",
    vacancyUrl: "https://dns-shop.ru/about/career",
  },
  {
    name: "М.Видео",
    slug: "mvideo",
    domain: "mvideo.ru",
    description: "Крупнейшая сеть электроники в России. Активно развивают e-commerce и omnichannel.",
    size: "15 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/mvideo.png",
    website: "https://mvideo.ru",
    vacancyUrl: "https://job.mvideo.ru",
  },

  // ─── Телеком ──────────────────────────────────────────────────────────────────
  {
    name: "МТС",
    slug: "mts",
    domain: "mts.ru",
    description: "Крупнейший телеком-оператор России. Активно трансформируются в IT-компанию: финтех, облако, AI.",
    size: "70 000+ сотрудников",
    tags: ["IT", "Телеком"],
    logoPath: "/logos/mts.svg",
    website: "https://mts.ru",
    vacancyUrl: "https://career.mts.ru",
  },
  {
    name: "Ростелеком",
    slug: "rostelecom",
    domain: "rostelecom.ru",
    description: "Национальный телекоммуникационный провайдер. Развивают облачные и цифровые сервисы.",
    size: "130 000+ сотрудников",
    tags: ["IT", "Телеком"],
    logoPath: "/logos/rostelecom.png",
    website: "https://rostelecom.ru",
    vacancyUrl: "https://hr.rt.ru",
  },
  {
    name: "МегаФон",
    slug: "megafon",
    domain: "megafon.ru",
    description: "Один из крупнейших мобильных операторов России. Активно развивают IT и цифровые сервисы.",
    size: "30 000+ сотрудников",
    tags: ["IT", "Телеком"],
    logoPath: "/logos/megafon.png",
    website: "https://megafon.ru",
    vacancyUrl: "https://rabota.megafon.ru",
  },
  {
    name: "Билайн",
    slug: "beeline",
    domain: "beeline.ru",
    description: "Крупный телеком-оператор, трансформирующийся в цифровую компанию.",
    size: "20 000+ сотрудников",
    tags: ["IT", "Телеком"],
    logoPath: "/logos/beeline.png",
    website: "https://beeline.ru",
    vacancyUrl: "https://beeline.ru/about/about-us/job",
  },
  {
    name: "Tele2",
    slug: "tele2",
    domain: "tele2.ru",
    description: "Телеком-оператор, известный инновационными продуктами и современной IT-культурой.",
    size: "5 000+ сотрудников",
    tags: ["IT", "Телеком"],
    logoPath: "/logos/tele2.png",
    website: "https://tele2.ru",
    vacancyUrl: "https://tele2.ru/about/career",
  },

  // ─── HR & Поиск работы ────────────────────────────────────────────────────────
  {
    name: "HeadHunter",
    slug: "hh",
    domain: "hh.ru",
    description: "Ведущая платформа для поиска работы в России. Ежедневно соединяют миллионы кандидатов и работодателей.",
    size: "2 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/hh.svg",
    website: "https://hh.ru",
    vacancyUrl: "https://hh.ru/employer/84585/vacancies",
  },
  {
    name: "Superjob",
    slug: "superjob",
    domain: "superjob.ru",
    description: "Крупная HR-платформа для поиска работы. Строят технологичный рекрутинговый сервис.",
    size: "1 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/superjob.png",
    website: "https://superjob.ru",
    vacancyUrl: "https://superjob.ru/about/company/job",
  },
  {
    name: "Работа.ру",
    slug: "rabotaru",
    domain: "rabota.ru",
    description: "Одна из крупнейших платформ для поиска работы в России.",
    size: "800+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/rabotaru.png",
    website: "https://rabota.ru",
    vacancyUrl: "https://rabota.ru/company/career",
  },
  {
    name: "Профи.ру",
    slug: "profiru",
    domain: "profi.ru",
    description: "Маркетплейс услуг, соединяющий профессионалов и клиентов по всей России.",
    size: "800+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/profiru.png",
    website: "https://profi.ru",
    vacancyUrl: "https://profi.ru/career",
  },

  // ─── Образование (EdTech) ─────────────────────────────────────────────────────
  {
    name: "Skyeng",
    slug: "skyeng",
    domain: "skyeng.ru",
    description: "Крупнейшая онлайн-школа английского языка в России.",
    size: "2 000+ сотрудников",
    tags: ["IT", "EdTech"],
    logoPath: "/logos/skyeng.svg",
    website: "https://skyeng.ru",
    vacancyUrl: "https://skyeng.ru/career",
  },
  {
    name: "Skillbox",
    slug: "skillbox",
    domain: "skillbox.ru",
    description: "Онлайн-университет для обучения IT-специальностям.",
    size: "3 000+ сотрудников",
    tags: ["IT", "EdTech"],
    logoPath: "/logos/skillbox.png",
    website: "https://skillbox.ru",
    vacancyUrl: "https://skillbox.ru/career",
  },
  {
    name: "Нетология",
    slug: "netology",
    domain: "netology.ru",
    description: "Онлайн-университет для цифровых профессий.",
    size: "1 000+ сотрудников",
    tags: ["IT", "EdTech"],
    logoPath: "/logos/netology.png",
    website: "https://netology.ru",
    vacancyUrl: "https://netology.ru/career",
  },
  {
    name: "GeekBrains",
    slug: "geekbrains",
    domain: "gb.ru",
    description: "Образовательная платформа для IT-специалистов. Программирование, Data Science, Design.",
    size: "800+ сотрудников",
    tags: ["IT", "EdTech"],
    logoPath: "/logos/geekbrains.png",
    website: "https://gb.ru",
    vacancyUrl: "https://gb.ru/career",
  },

  // ─── Медиа & Развлечения ──────────────────────────────────────────────────────
  {
    name: "Дзен",
    slug: "dzen",
    domain: "dzen.ru",
    description: "Платформа персонализированного контента. Используют ML и рекомендательные алгоритмы.",
    size: "1 000+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/dzen.png",
    website: "https://dzen.ru",
    vacancyUrl: "https://yandex.ru/jobs",
  },
  {
    name: "ivi",
    slug: "ivi",
    domain: "ivi.ru",
    description: "Крупнейший российский видеосервис с миллионами подписчиков.",
    size: "1 000+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/ivi.png",
    website: "https://ivi.ru",
    vacancyUrl: "https://company.ivi.ru/career",
  },
  {
    name: "Кинопоиск",
    slug: "kinopoisk",
    domain: "kinopoisk.ru",
    description: "Ведущий кино- и сериальный сервис России от Яндекса.",
    size: "500+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/kinopoisk.png",
    website: "https://kinopoisk.ru",
    vacancyUrl: "https://yandex.ru/jobs",
  },
  {
    name: "START",
    slug: "start",
    domain: "start.ru",
    description: "Российская стриминговая платформа с оригинальным контентом.",
    size: "500+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/start.png",
    website: "https://start.ru",
    vacancyUrl: "https://start.ru/careers",
  },
  {
    name: "RuTube",
    slug: "rutube",
    domain: "rutube.ru",
    description: "Российская видеоплатформа. Активно развивают технологии для видеохостинга.",
    size: "500+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/rutube.png",
    website: "https://rutube.ru",
    vacancyUrl: "https://rutube.ru/career",
  },

  // ─── Недвижимость ─────────────────────────────────────────────────────────────
  {
    name: "Циан",
    slug: "cian",
    domain: "cian.ru",
    description: "Крупнейшая платформа для поиска недвижимости в России. Помогают миллионам найти дом или офис.",
    size: "1 500+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/cian.png",
    website: "https://cian.ru",
    vacancyUrl: "https://cian.ru/career",
  },

  // ─── Логистика ────────────────────────────────────────────────────────────────
  {
    name: "СДЭК",
    slug: "cdek",
    domain: "cdek.ru",
    description: "Один из крупнейших логистических операторов России. Развивают IT-платформу.",
    size: "30 000+ сотрудников",
    tags: ["IT", "Логистика"],
    logoPath: "/logos/cdek.png",
    website: "https://cdek.ru",
    vacancyUrl: "https://cdek.ru/ru/pages/job",
  },
  {
    name: "Boxberry",
    slug: "boxberry",
    domain: "boxberry.ru",
    description: "Сеть пунктов выдачи и курьерская доставка. Строят технологичную логистику.",
    size: "5 000+ сотрудников",
    tags: ["IT", "Логистика"],
    logoPath: "/logos/boxberry.png",
    website: "https://boxberry.ru",
    vacancyUrl: "https://boxberry.ru/about/career",
  },
  {
    name: "Почта России",
    slug: "pochta",
    domain: "pochta.ru",
    description: "Государственный почтовый оператор. Масштабная IT-трансформация и цифровизация.",
    size: "300 000+ сотрудников",
    tags: ["IT", "Логистика"],
    logoPath: "/logos/pochta.png",
    website: "https://pochta.ru",
    vacancyUrl: "https://career.pochta.ru",
  },

  // ─── HealthTech ───────────────────────────────────────────────────────────────
  {
    name: "Сберздоровье",
    slug: "sberhealth",
    domain: "sberhealth.ru",
    description: "Телемедицинская платформа от Сбера. Онлайн-консультации и медицинские сервисы.",
    size: "1 000+ сотрудников",
    tags: ["IT", "HealthTech"],
    logoPath: "/logos/sberhealth.png",
    website: "https://sberhealth.ru",
    vacancyUrl: "https://sberhealth.ru/about/careers",
  },
  {
    name: "DocDoc",
    slug: "docdoc",
    domain: "docdoc.ru",
    description: "Сервис для записи к врачу и телемедицины.",
    size: "300+ сотрудников",
    tags: ["IT", "HealthTech"],
    logoPath: "/logos/docdoc.png",
    website: "https://docdoc.ru",
    vacancyUrl: "https://docdoc.ru/about/career",
  },
  {
    name: "BestDoctor",
    slug: "bestdoctor",
    domain: "bestdoctor.ru",
    description: "Платформа корпоративного здравоохранения нового поколения.",
    size: "400+ сотрудников",
    tags: ["IT", "HealthTech"],
    logoPath: "/logos/bestdoctor.png",
    website: "https://bestdoctor.ru",
    vacancyUrl: "https://bestdoctor.ru/careers",
  },

  // ─── Корпоративный IT & Промышленность ───────────────────────────────────────
  {
    name: "X5 Tech",
    slug: "x5tech",
    domain: "x5-tech.ru",
    description: "IT-подразделение X5 Group (Пятёрочка, Перекрёсток). Ритейл-технологии и автоматизация.",
    size: "5 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/x5tech.png",
    website: "https://x5-tech.ru",
    vacancyUrl: "https://x5-tech.ru/career",
  },
  {
    name: "Магнит",
    slug: "magnit",
    domain: "magnit.ru",
    description: "Крупнейшая розничная сеть с активной IT-трансформацией.",
    size: "320 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/magnit.png",
    website: "https://magnit.ru",
    vacancyUrl: "https://magnit.ru/about/career",
  },
  {
    name: "СИБУР",
    slug: "sibur",
    domain: "sibur.ru",
    description: "Крупнейший нефтехимический холдинг России. Развивают СИБУР Диджитал.",
    size: "20 000+ сотрудников",
    tags: ["IT", "Промышленность"],
    logoPath: "/logos/sibur.png",
    website: "https://sibur.ru",
    vacancyUrl: "https://career.sibur.ru",
  },
  {
    name: "Аэрофлот",
    slug: "aeroflot",
    domain: "aeroflot.ru",
    description: "Национальный авиаперевозчик. Развивают IT-платформу и цифровые сервисы.",
    size: "20 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/aeroflot.png",
    website: "https://aeroflot.ru",
    vacancyUrl: "https://career.aeroflot.ru",
  },
  {
    name: "Газпром Нефть",
    slug: "gazpromneft",
    domain: "gazprom-neft.ru",
    description: "Нефтяная компания с масштабным IT-подразделением. Цифровизация нефтедобычи.",
    size: "70 000+ сотрудников",
    tags: ["IT", "Промышленность"],
    logoPath: "/logos/gazpromneft.png",
    website: "https://gazprom-neft.ru",
    vacancyUrl: "https://career.gazprom-neft.ru",
  },
  {
    name: "Битрикс24",
    slug: "bitrix24",
    domain: "bitrix24.ru",
    description: "CRM-система и корпоративный портал для управления бизнесом.",
    size: "1 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/bitrix24.png",
    website: "https://bitrix24.ru",
    vacancyUrl: "https://bitrix24.ru/about/career.php",
  },
  {
    name: "EPAM Systems",
    slug: "epam",
    domain: "epam.com",
    description: "Глобальная IT-компания с российскими корнями. Разработка ПО для мировых брендов.",
    size: "50 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/epam.png",
    website: "https://epam.com",
    vacancyUrl: "https://careers.epam.ru",
  },

  // ─── Геймдев ──────────────────────────────────────────────────────────────────
  {
    name: "MY.GAMES",
    slug: "mygames",
    domain: "my.games",
    description: "Один из крупнейших игровых издателей России и СНГ. Разрабатывают мобильные и PC-игры.",
    size: "3 000+ сотрудников",
    tags: ["IT", "Геймдев"],
    logoPath: "/logos/mygames.png",
    website: "https://my.games",
    vacancyUrl: "https://my.games/careers",
  },
  {
    name: "Wargaming",
    slug: "wargaming",
    domain: "wargaming.net",
    description: "Мировой разработчик игр, создавший World of Tanks.",
    size: "5 000+ сотрудников",
    tags: ["IT", "Геймдев"],
    logoPath: "/logos/wargaming.png",
    website: "https://wargaming.net",
    vacancyUrl: "https://wargaming.com/ru/career",
  },
  {
    name: "Gaijin",
    slug: "gaijin",
    domain: "gaijin.net",
    description: "Разработчик War Thunder и других популярных игр. Независимая игровая студия.",
    size: "1 500+ сотрудников",
    tags: ["IT", "Геймдев"],
    logoPath: "/logos/gaijin.png",
    website: "https://gaijin.net",
    vacancyUrl: "https://jobs.gaijin.net",
  },
  {
    name: "VK Play",
    slug: "vkplay",
    domain: "vkplay.ru",
    description: "Игровая платформа и облако VK. Эксклюзивный игровой контент и стриминг.",
    size: "500+ сотрудников",
    tags: ["IT", "Геймдев", "Медиа"],
    logoPath: "/logos/vkplay.png",
    website: "https://vkplay.ru",
    vacancyUrl: "https://jobs.vk.company",
  },

  // ─── Трэвел & Мобильность ─────────────────────────────────────────────────────
  {
    name: "Туту.ру",
    slug: "tutu",
    domain: "tutu.ru",
    description: "Онлайн-сервис покупки билетов и планирования путешествий.",
    size: "500+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/tutu.png",
    website: "https://tutu.ru",
    vacancyUrl: "https://tutu.ru/about/career",
  },
  {
    name: "OneTwoTrip",
    slug: "onetwotrip",
    domain: "onetwotrip.ru",
    description: "Онлайн-трэвел агентство для бронирования авиа, отелей и туров.",
    size: "500+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/onetwotrip.png",
    website: "https://onetwotrip.ru",
    vacancyUrl: "https://onetwotrip.com/ru/about/career",
  },
  {
    name: "Whoosh",
    slug: "whoosh",
    domain: "whoosh.bike",
    description: "Крупнейший кикшеринговый сервис в России. Активно развивают технологическую платформу.",
    size: "1 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/whoosh.png",
    website: "https://whoosh.bike",
    vacancyUrl: "https://whoosh.bike/career",
  },
  {
    name: "InDriver",
    slug: "indriver",
    domain: "indriver.com",
    description: "Международный райдхейлинговый сервис, основанный в Якутии. Работают в 40+ странах.",
    size: "5 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/indriver.png",
    website: "https://indriver.com",
    vacancyUrl: "https://indriver.com/page/career",
  },

  // ─── Дополнительные компании ──────────────────────────────────────────────────
  {
    name: "KazanExpress",
    slug: "kazanexpress",
    domain: "kazan.express",
    description: "Быстрорастущий маркетплейс с фокусом на скорости доставки и собственной логистикой.",
    size: "5 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/kazanexpress.png",
    website: "https://kazan.express",
    vacancyUrl: "https://kazan.express/career",
  },
  {
    name: "ВкусВилл",
    slug: "vkusvill",
    domain: "vkusvill.ru",
    description: "Сеть магазинов с IT-трансформацией. Один из лидеров продуктовой разработки в ритейле.",
    size: "15 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/vkusvill.png",
    website: "https://vkusvill.ru",
    vacancyUrl: "https://vkusvill.ru/career",
  },
  {
    name: "Одноклассники",
    slug: "ok",
    domain: "ok.ru",
    description: "Вторая по размеру социальная сеть в России. Часть экосистемы VK.",
    size: "1 000+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/ok.png",
    website: "https://ok.ru",
    vacancyUrl: "https://jobs.vk.company",
  },
  {
    name: "Okko",
    slug: "okko",
    domain: "okko.tv",
    description: "Стриминговый сервис с широкой библиотекой фильмов и сериалов. Развивают рекомендательные алгоритмы.",
    size: "500+ сотрудников",
    tags: ["IT", "Медиа"],
    logoPath: "/logos/okko.png",
    website: "https://okko.tv",
    vacancyUrl: "https://okko.tv/career",
  },
  {
    name: "Яндекс Go",
    slug: "yandexgo",
    domain: "go.yandex",
    description: "Суперприложение для мобильности: такси, курьерская доставка, каршеринг.",
    size: "10 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/yandexgo.png",
    website: "https://go.yandex",
    vacancyUrl: "https://yandex.ru/jobs",
  },
  {
    name: "Купер",
    slug: "kuper",
    domain: "kuper.ru",
    description: "Сервис экспресс-доставки продуктов из магазинов. Бывший СберМаркет.",
    size: "5 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/kuper.png",
    website: "https://kuper.ru",
    vacancyUrl: "https://kuper.ru/career",
  },
  {
    name: "Luxoft",
    slug: "luxoft",
    domain: "luxoft.com",
    description: "Глобальная IT-компания с российскими корнями. Разработка ПО для финансового сектора.",
    size: "15 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/luxoft.png",
    website: "https://luxoft.com",
    vacancyUrl: "https://career.luxoft.com",
  },
  {
    name: "DataArt",
    slug: "dataart",
    domain: "dataart.com",
    description: "IT-консалтинг и разработка ПО. Известны высокой инженерной культурой.",
    size: "4 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/dataart.png",
    website: "https://dataart.com",
    vacancyUrl: "https://www.dataart.com/ru/career",
  },
  {
    name: "ЦФТ",
    slug: "cft",
    domain: "cftonline.ru",
    description: "Один из крупнейших разработчиков банковского ПО в России.",
    size: "3 000+ сотрудников",
    tags: ["IT", "Финтех"],
    logoPath: "/logos/cft.png",
    website: "https://cftonline.ru",
    vacancyUrl: "https://cftonline.ru/o-kompanii/vakansii",
  },
  {
    name: "Самолёт",
    slug: "samolet",
    domain: "samolet.ru",
    description: "Крупнейший застройщик России с передовой PropTech-платформой.",
    size: "3 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/samolet.png",
    website: "https://samolet.ru",
    vacancyUrl: "https://samolet.ru/career",
  },
  {
    name: "МТС Линк",
    slug: "mtslink",
    domain: "mtslink.ru",
    description: "Платформа для видеоконференций и совместной работы от МТС.",
    size: "500+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/mtslink.png",
    website: "https://mtslink.ru",
    vacancyUrl: "https://career.mts.ru",
  },
  {
    name: "Яндекс Практикум",
    slug: "practicum",
    domain: "practicum.yandex.ru",
    description: "Обучение IT-профессиям от Яндекса. Разрабатывают продукт, обучающий тысячи студентов.",
    size: "1 000+ сотрудников",
    tags: ["IT", "EdTech"],
    logoPath: "/logos/practicum.png",
    website: "https://practicum.yandex.ru",
    vacancyUrl: "https://yandex.ru/jobs",
  },
  {
    name: "ELMA365",
    slug: "elma",
    domain: "elma365.com",
    description: "Российская low-code платформа для автоматизации бизнес-процессов.",
    size: "500+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/elma.png",
    website: "https://elma365.com",
    vacancyUrl: "https://elma365.com/ru/career",
  },
  {
    name: "Softline",
    slug: "softline",
    domain: "softline.ru",
    description: "Один из лидеров российского IT-рынка. Дистрибуция ПО, облачные сервисы, интеграция.",
    size: "8 000+ сотрудников",
    tags: ["IT"],
    logoPath: "/logos/softline.png",
    website: "https://softline.ru",
    vacancyUrl: "https://softline.ru/about/career",
  },
  {
    name: "Fix Price",
    slug: "fixprice",
    domain: "fix-price.ru",
    description: "Крупнейшая сеть магазинов фиксированных цен. Активно развивают e-commerce и ритейл-тех.",
    size: "20 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/fixprice.png",
    website: "https://fix-price.ru",
    vacancyUrl: "https://fix-price.ru/about/career",
  },
  {
    name: "Nexign",
    slug: "nexign",
    domain: "nexign.com",
    description: "Разработчик телекоммуникационного ПО. Биллинговые системы и платформы для операторов связи.",
    size: "2 000+ сотрудников",
    tags: ["IT", "Телеком"],
    logoPath: "/logos/nexign.png",
    website: "https://nexign.com",
    vacancyUrl: "https://nexign.com/ru/careers",
  },
  {
    name: "Яндекс Маркет",
    slug: "yandexmarket",
    domain: "market.yandex.ru",
    description: "Маркетплейс Яндекса. Один из крупнейших e-commerce игроков с собственной логистикой.",
    size: "7 000+ сотрудников",
    tags: ["IT", "E-commerce"],
    logoPath: "/logos/yandexmarket.png",
    website: "https://market.yandex.ru",
    vacancyUrl: "https://yandex.ru/jobs",
  },
];

export const COMPANIES = COMPANIES_META.map((c) => c.name);

export const ROLES = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "iOS Developer",
  "Android Developer",
  "Data Engineer",
  "ML Engineer",
  "DevOps / SRE",
  "QA Engineer",
  "Product Manager",
  "Designer",
];

export const FAQS = [
  {
    q: "Что такое реферал и зачем он нужен?",
    a: "Реферал — это рекомендация от действующего сотрудника компании. Кандидаты с рефералом рассматриваются в приоритете и с вероятностью до 40% чаще получают оффер.",
  },
  {
    q: "Гарантируете ли вы оффер?",
    a: "Нет. Мы гарантируем реферал — то есть твоё резюме попадёт к рекрутеру напрямую через сотрудника. Оффер зависит от тебя.",
  },
  {
    q: "Как быстро найдут реферера?",
    a: "Обычно в течение 1–3 рабочих дней. Если нужного реферера нет — сообщим честно.",
  },
  {
    q: "Кто эти рефереры и можно ли им доверять?",
    a: "Это реальные сотрудники компаний, которые зарегистрировались на платформе. Мы проверяем их вручную.",
  },
  {
    q: "Как отменить подписку?",
    a: "В любой момент через личный кабинет или написав в поддержку. Деньги за текущий период не возвращаются.",
  },
];

export const MOCK_CANDIDATES = [
  {
    id: "1",
    role: "Frontend Developer",
    stack: ["React", "TypeScript", "Next.js"],
    experience: 4,
    companies: ["Яндекс", "Авито"],
  },
  {
    id: "2",
    role: "Backend Developer",
    stack: ["Go", "PostgreSQL", "Kafka"],
    experience: 6,
    companies: ["Т-Банк", "Озон"],
  },
  {
    id: "3",
    role: "ML Engineer",
    stack: ["Python", "PyTorch", "Airflow"],
    experience: 3,
    companies: ["Яндекс", "Сбер"],
  },
  {
    id: "4",
    role: "iOS Developer",
    stack: ["Swift", "SwiftUI", "Combine"],
    experience: 5,
    companies: ["ВКонтакте", "Авито"],
  },
];
